

EASTER_EGG = {"Hasta La Vista, baby" : "Terminator 2: Judgement Day",
              "Say 'hello' to my little friend" : "Scarface",
              "Greed, for lack of a better word, is Good" : "Wall Street",
              "After all, tomorrow is another day" : "Gone with the Wind",
              "I'm gonna make him an offer he can't refuse" : "The Godfather",
              "Toto, I've a felling we're not in Kansas anymore" : "The Wizard of Oz",
              "Go ahead, make my day" : "Sudden Impact",
              "Alright, Mr. DeMille, I'm ready for my close-up" : "Sunset Blvd",
              "You talking to me?" : "Taxi Driver",
              "What we've got here is failure to communicate" : "Cool Hand Luke",
              "I love the smell of napalm in the morning" : "Apocalypse Now",
              "Love means never having to say you're sorry" : "Love Story",
              "The stuff that dreams are made of" : "The Maltese Falcon",
              "Rosebud" : "Citizen Kane",
              "Luis, I think this is the beginning of a beautiful friendship" : "Casablanca",
              "You can't handle the truth" : "A Few Good Men",
              "I'll have what she's having" : "When Harry Met Sally",
              "My mama always said life was like a box of chocolates. You never know what you're gonna get" : "Forrest Gump",
              "We rob banks" : "Bonnie and Clyde",
              "Houston, we have a problem" : "Apollo 13",
              "Keep your friends close, but your enemies closer" : "The Godfather II",
              "Mrs. Robinson, you're trying to seduce me. Arent you" : "The Graduate",
              "Fools names and fools faces" : "Chinatown",
              "Never send a human to do a machine's job" : "The Matrix",
              "If he dies, he dies" : "Rocky IV",
              "You can be my wingman anytime" : "Top Gun",
              "College women can smell ignorance... like dog shit" : "Risky Business",
              "Dead or alive, you're coming with me!" : "RoboCop",
              "I don't make things complicated. That's the way they get, all by themselves" : "Lethal Weapon",
              "In here every men gets to be Cary Grant" : "Air America",
              "I was wetter then Drew Barrymore at a grunge club" : "Kiss Kiss Bang Bang",
              "Honey, c'mon over here sugarbuns. This machine just called me an asshole" : "Maximum Overdrive",
              "I got vision and the rest of the world wears bifocals" : "Butch Cassidy and the Sundance Kid",
              "You got more metal inside you than a ten ton truck" : "Drive",
              "Sounded like a big V-8 to me. I guess I got myself some guzzolene" : "Mad Max 2: The Road Warrior",
              "I'm ready to kick your ass out of this world, war hero" : "Escape from New York",
              "The whole world's gonna smell like Momma June after hot yoga" : "Deadpool",
              "Popularity is just the slutty little cousin of prestige" : "Birdman",
              "Army coudn't find it's cock if it had a hard-on" : "Rambo: 'First Blood'",
              "Poor people are crazy. I'm eccentric" : "Speed",
              "Warriors, come out to play" : "The Warriors",
              "You're a real blue-flame special, aren't you, Utah?" : "Point Break",
              "It's 106 miles to Chicago, we got a full tank of gas, half a pack of cigarettes, it's dark... and we're wearing sunglasses." : "The Blues Brothers",
              "The dead know only one thing: it is better to be alive" : "Full Metal Jacket",
              "Goodness is something to be chosen. When a man cannot choose he ceases to be a man" : "A Clockwork Orange",
              "I'll be there in two shakes of a lamb's tail" : "Pulp Fiction",
              "I guess it comes down to a simple choice, really. Get busy living, or get busy dying" : "The Shawshank Redemption",
              "Is life always this hard, or is it just when you're a kid?" : "Leon: The Professional",
              "Every man dies, not every man really lives" : "Braveheart",
              "Look what this fucking mutt did to my shoes" : "Goodfellas",
              "Well, Clarice - have the lambs stopped screaming?" : "The Silence of the Lambs"
              }
